services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    
  mongo:
    image: mongo:8.0.5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - kafka-net

  urblog:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongo
    networks:
      - kafka-net
    environment:
      DATABASE: mongo
      MONGODB_URI: mongodb://mongo:27017/urblog
      KAFKA_BROKER: kafka:9092
    volumes:
      - ./docs:/app/docs

networks:
  kafka-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local