services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "ruok,srvr,mntr,conf,cons,stat"
      ZOO_LOG4J_PROP: "ERROR, CONSOLE"
      ZOO_LOG_LEVEL: "ERROR"

    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "echo srvr | nc localhost 2181 | grep 'Mode' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  kafka:
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://urblog-kafka-1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: "INFO"
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server urblog-kafka-1:9092 | grep 'id:' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  mongo:
    image: mongo:8.0.5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping: 1})"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: mongod --quiet --logpath /dev/null
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  urblog:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - kafka-net
    environment:
      MONGODB_URI: mongodb://mongo:27017/urblog
      KAFKA_BROKER: kafka:9092
    volumes:
      - ./docs:/app/docs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  kafka-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local