name: CI

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: Upload coverage to Coverage Robot
        uses: coverage-robot/action@v1.0.8
        with:
          files: coverage.out
          tag: ${{ github.sha }}
          token: ${{ secrets.COVERAGE_ROBOT_TOKEN }}
          endpoint: https://api.coveragerobot.com/v1
          github-token: ${{ github.token }}

      - name: Clean up existing files
        run: |
          echo "Cleaning up existing files..."
          rm -rf ../../../go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/*

      - name: Handle tar errors
        run: |
          tar -xvf your_tar_file.tar.gz || {
            echo "Tar extraction failed, retrying..."
            rm -rf ../../../go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/*
            tar -xvf your_tar_file.tar.gz
          }